class AirportCodes {
  // Map of city names to airport IATA codes
  static final Map<String, String> cityToAirport = {
    'cairo': 'CAI',
    'dubai': 'DXB',
    'istanbul': 'IST',
    'doha': 'DOH',
    'abu dhabi': 'AUH',
    'london': 'LHR',
    'new york': 'JFK',
    'paris': 'CDG',
    'frankfurt': 'FRA',
    'amsterdam': 'AMS',
    'los angeles': 'LAX',
    'tokyo': 'NRT',
    'sydney': 'SYD',
    'bangkok': 'BKK',
    'rome': 'FCO',
    'bali': 'DPS',
    'barcelona': 'BCN',
    'milan': 'MXP',
    'madrid': 'MAD',
    'munich': 'MUC',
    'zurich': 'ZRH',
    'vienna': 'VIE',
    'athens': 'ATH',
    'lisbon': 'LIS',
    'dublin': 'DUB',
    'stockholm': 'ARN',
    'copenhagen': 'CPH',
    'oslo': 'OSL',
    'helsinki': 'HEL',
    'warsaw': 'WAW',
    'prague': 'PRG',
    'budapest': 'BUD',
    'bucharest': 'OTP',
    'sao paulo': 'GRU',
    'rio de janeiro': 'GIG',
    'mexico city': 'MEX',
    'buenos aires': 'EZE',
    'santiago': 'SCL',
    'lima': 'LIM',
    'bogota': 'BOG',
    'caracas': 'CCS',
    'montreal': 'YUL',
    'toronto': 'YYZ',
    'vancouver': 'YVR',
    'chicago': 'ORD',
    'miami': 'MIA',
    'san francisco': 'SFO',
    'seattle': 'SEA',
    'boston': 'BOS',
    'washington': 'IAD',
    'atlanta': 'ATL',
    'dallas': 'DFW',
    'houston': 'IAH',
    'phoenix': 'PHX',
    'denver': 'DEN',
    'las vegas': 'LAS',
    'hong kong': 'HKG',
    'singapore': 'SIN',
    'kuala lumpur': 'KUL',
    'jakarta': 'CGK',
    'manila': 'MNL',
    'ho chi minh city': 'SGN',
    'hanoi': 'HAN',
    'seoul': 'ICN',
    'beijing': 'PEK',
    'shanghai': 'PVG',
    'guangzhou': 'CAN',
    'shenzhen': 'SZX',
    'chengdu': 'CTU',
    'xian': 'XIY',
    'mumbai': 'BOM',
    'delhi': 'DEL',
    'bangalore': 'BLR',
    'hyderabad': 'HYD',
    'chennai': 'MAA',
    'kolkata': 'CCU',
    'pune': 'PNQ',
    'ahmedabad': 'AMD',
    'kochi': 'COK',
    'thiruvananthapuram': 'TRV',
    'goa': 'GOI',
    'jaipur': 'JAI',
    'udaipur': 'UDR',
    'varanasi': 'VNS',
    'lucknow': 'LKO',
    'indore': 'IDR',
    'bhopal': 'BHO',
    'nagpur': 'NAG',
    'raipur': 'RPR',
    'bhubaneswar': 'BBI',
    'visakhapatnam': 'VTZ',
    'vijayawada': 'VGA',
    'rajahmundry': 'RJA',
    'tirupati': 'TIR',
    'coimbatore': 'CJB',
    'madurai': 'IXM',
    'trichy': 'TRZ',
    'salem': 'SXV',
    'pondicherry': 'PNY',
    'tuticorin': 'TCR',
    'thoothukudi': 'TCR',
    'nagercoil': 'NVY',
    'kanniyakumari': 'NVY',
    'kanyakumari': 'NVY',
    'theni': 'TEN',
    'dindigul': 'DGL',
    'karur': 'KRR',
    'namakkal': 'NMK',
    'erode': 'ERD',
    'tiruppur': 'TIR',
    'salem': 'SXV',
    'hosur': 'HSR',
    'krishnagiri': 'KRI',
    'dharmapuri': 'DHP',
    'vellore': 'VLR',
    'ranipet': 'RNT',
    'arani': 'ARN',
    'cheyyar': 'CYR',
    'tindivanam': 'TDV',
    'villupuram': 'VPM',
    'cuddalore': 'CDL',
    'chidambaram': 'CDM',
    'kumbakonam': 'KBM',
    'mayiladuthurai': 'MYL',
    'nagapattinam': 'NGP',
    'karaikal': 'KRK',
    'thanjavur': 'TJV',
    'pattukkottai': 'PTK',
    'peravurani': 'PRV',
    'arangasamudram': 'AGM',
    'manargudi': 'MGR',
    'muthupet': 'MTP',
    'adanakottai': 'ADK',
    'devakottai': 'DVK',
    'karaikudi': 'KRD',
    'sivaganga': 'SVG',
    'manamadurai': 'MNM',
    'paramakudi': 'PMK',
    'ramanathapuram': 'RMD',
    'kilakarai': 'KKR',
    'thondi': 'TND',
    'valinokkam': 'VNK',
    'pasipattinam': 'PSP',
    'mandapam': 'MPM',
    'pamban': 'PBN',
    'rameswaram': 'RWS',
    'udukottai': 'UDK',
    'pudukkottai': 'PDK',
    'alangudi': 'ALG',
    'arantangi': 'ARG',
    'avudaiyar koil': 'AVK',
    'gandarvakottai': 'GDK',
    'illuppur': 'ILP',
    'karambakudi': 'KRB',
    'keeranur': 'KRR',
    'kunnandarkoil': 'KNK',
    'kulathur': 'KLT',
    'manamelkudi': 'MNK',
    'mathur': 'MTR',
    'nalam': 'NLM',
    'pallathur': 'PLT',
    'ponnamaravathi': 'PNM',
    'pudukkottai': 'PDK',
    'santhanakudi': 'SNK',
    'sirugudi': 'SRG',
    'thirumayam': 'TMY',
    'viralimalai': 'VRM',
    'ponnamaravathi': 'PNM',
    'aranthangi': 'ARG',
    'illuppur': 'ILP',
    'karambakudi': 'KRB',
    'keeranur': 'KRR',
    'kunnandarkoil': 'KNK',
    'kulathur': 'KLT',
    'manamelkudi': 'MNK',
    'mathur': 'MTR',
    'nalam': 'NLM',
    'pallathur': 'PLT',
    'ponnamaravathi': 'PNM',
    'santhanakudi': 'SNK',
    'sirugudi': 'SRG',
    'thirumayam': 'TMY',
    'viralimalai': 'VRM',
  };

  /// Get airport code from city name
  static String? getAirportCode(String cityName) {
    final normalized = cityName.toLowerCase().trim();
    return cityToAirport[normalized];
  }

  /// Check if a string is an airport code (3 uppercase letters)
  static bool isAirportCode(String code) {
    return code.length == 3 &&
        code.toUpperCase() == code &&
        code.contains(RegExp(r'^[A-Z]{3}$'));
  }

  /// Try to get airport code, returns the input if it's already a code
  static String getAirportCodeOrInput(String input) {
    // If it's already an airport code, return it
    if (isAirportCode(input)) {
      return input.toUpperCase();
    }

    // Try to find airport code from city name
    final code = getAirportCode(input);
    if (code != null) {
      return code;
    }

    // If not found, return uppercase input (user might have entered a code)
    return input.toUpperCase();
  }
}
